version: 0.2
phases:
  build:
    commands:
      - echo "Deploying CloudFormation Stack"
      - aws cloudformation deploy --template-file template.yaml --stack-name YourStackName --capabilities CAPABILITY_NAMED_IAM
