AWSTemplateFormatVersion: '2010-09-09'
Description: 2-Tier Architecture with EC2 and RDS

Resources:
  # Web Layer (EC2 Instances)
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Enable SSH and HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: '0.0.0.0/0'
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: '0.0.0.0/0'

  WebInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c55b159cbfafe1f0  # Update with your preferred AMI
      SecurityGroups: 
        - Ref: WebSecurityGroup
      KeyName: your-key-pair  # Replace with your key pair name

  # Database Layer (RDS Instance)
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: mydatabase
      Engine: mysql
      DBInstanceClass: db.t2.micro
      AllocatedStorage: '20'
      MasterUsername: admin
      MasterUserPassword: 'yourpassword'
      VPCSecurityGroups:
        - Ref: WebSecurityGroup

Outputs:
  WebInstancePublicIP:
    Description: Public IP of the web instance
    Value: !GetAtt WebInstance.PublicIp
